
services:
  server:
    build:
      context: .
      dockerfile: configs/server/Dockerfile
    ports:
      - "50555:50555"
    networks:
      - net1

  client:
    build:
      context: .
      dockerfile: configs/client/Dockerfile  
    networks:
      - net1

networks:
  net1:
